apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: users-and-groups
spec:
  type: file
  targets:
    #- ./users/solunkeyogesh.yaml
    - https://raw.githubusercontent.com/solunkeyogesh/sample-backstage-repo/main/catalog/users/solunkeyogesh.yaml
    - https://raw.githubusercontent.com/solunkeyogesh/sample-backstage-repo/main/catalog/groups/engineering.yaml
    #- ./groups/engineering.yaml
  rules:
    - allow: [User, Group]
