apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: users-and-groups
spec:
  type: url
  targets:
    - users/solunkeyogesh.yaml
    - groups/engineering.yaml
  rules:
    - allow: [User, Group]
